
CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	username TEXT NOT NULL UNIQUE,
	password_hash TEXT NOT NULL
);

CREATE INDEX ix_user_username ON user (username);

CREATE TABLE drawing (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	user_id INTEGER NOT NULL,
	data TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES user(id)
);